name: Tests

on:
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GH_PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r exec/aws-apprunner/requirements.txt
        # Install additional dependencies for evals
        pip install openai tiktoken
    
    - name: Run all tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CI: true
      run: |
        # Install just task runner
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # Run comprehensive test suite using justfile
        # Try full pipeline if data is available, otherwise just config validation
        just full-pipeline || just validate-config
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          target/
          logs/
          *.log
        retention-days: 7
